"""Stage 3.1 regressions: future-delivery sales are timed events."""
import os
import sys
from datetime import timedelta

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import app as m
from app import Engine
from core import hypothetical as H
from core import offers as OF
from core.plan_model import PlanModel, Scenario

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "data", "test_stage31.db")


@pytest.fixture(scope="module")
def E():
    for ext in ("", "-wal", "-shm"):
        if os.path.exists(DB + ext):
            os.remove(DB + ext)
    eng = Engine(DB)
    m.ENGINE = eng
    yield eng
    eng.db.close()


def ctx(E):
    H.cache_clear()
    return E.ctx()


def cohort(E):
    st = E.ctx()[2]
    cs = [c for c in st.cohorts.values() if c.alive > 20_000 and c.mean_weight >= 1.0]
    return max(cs, key=lambda c: c.alive)


def test_sale_today_vs_30_days_later(E):
    """Today removes now; +30d remains live and becomes a scheduled event."""
    A, bio, st = ctx(E)
    c = cohort(E)
    q = min(10_000.0, c.alive * 0.1)
    price = 18_000.0
    future = st.as_of + timedelta(days=30)
    alloc = [{"cohort_id": c.cohort_id, "quantity": q}]

    today = st.clone()
    today_rows = OF._apply_sale_timing(A, today, alloc, q, price, st.as_of, {}, c.mean_weight)
    assert today.cohorts[c.cohort_id].alive == pytest.approx(c.alive - q, abs=1)
    assert any(r["amount"] > 0 for r in today_rows)

    later = st.clone()
    later_rows = OF._apply_sale_timing(A, later, alloc, q, price, future, {},
                                       st.weight_of(c, future))
    assert later.cohorts[c.cohort_id].alive == pytest.approx(c.alive, abs=1)
    assert later_rows == []  # default payment terms are generated by timed plan revenue
    assert any(e["type"] == "scheduled_sale" and e["date"] == future.isoformat()
               for e in later.hypothetical_events)

    # The future-sale profile still incurs feed/mortality before delivery.
    model = PlanModel(A, bio, later)
    p = model.existing_profile(later.cohorts[c.cohort_id], 15.0, Scenario.base())
    delivery_week = (30 + 6) // 7
    assert sum(p.feed_kg[1:delivery_week + 1]) > 0
    assert sum(p.mortality[1:delivery_week + 1]) >= 0
    assert p.harvest_fish[delivery_week] > 0


def test_ponds_freed_zero_before_delivery_then_applied(E):
    """Committed fish occupy pond capacity until delivery, then capacity drops."""
    A, bio, st = ctx(E)
    c = cohort(E)
    cap = max(1.0, bio.fish_per_pond(c.mean_weight))
    q = min(c.alive * 0.45, max(2_000.0, cap * 1.05))
    future = st.as_of + timedelta(days=30)

    st2 = st.clone()
    before_now = H.integer_ponds_now(st2)
    H.schedule_sale(st2, [{"cohort_id": c.cohort_id, "quantity": q}],
                    18_000.0, future, st.weight_of(c, future))
    # Scheduling alone cannot free a pond today.
    assert H.integer_ponds_now(st2) == before_now

    model = PlanModel(A, bio, st2)
    p = model.existing_profile(st2.cohorts[c.cohort_id], 15.0, Scenario.base())
    delivery_week = (30 + 6) // 7
    assert model.grid.dates[delivery_week] >= future
    assert p.fish[delivery_week - 1] > p.fish[delivery_week]
    assert p.ponds[delivery_week - 1] >= p.ponds[delivery_week]
    assert p.harvest_fish[delivery_week] > 0


def test_custom_payment_terms_start_no_earlier_than_delivery(E):
    A, bio, st = ctx(E)
    c = cohort(E)
    q = 5_000.0
    future = st.as_of + timedelta(days=30)
    st2 = st.clone()
    rows = OF._apply_sale_timing(
        A, st2, [{"cohort_id": c.cohort_id, "quantity": q}], q, 18_000.0, future,
        {"upfront_share": 0.25, "delay_days": 60}, st.weight_of(c, future))
    assert rows
    assert min(H.d(r["date"]) for r in rows if r["amount"] > 0) >= future
